### ISSUE TITLE
Add "Consulting" and "Portfolio" tabs to the website

### ISSUE THREAD

**Issue by njlyon0** [njlyon0/njlyon0.github.io#4]
## Task Overview

Want to add a consulting tab and a portfolio tab to my website

### Tasks

- [ ] Portfolio tab
    - [ ] Identify 2-3 examples of past work to embed in tab (see "career.qmd")
    - [ ] Write brief blurb for each example
    - [ ] Include links and maybe nice screencap of product
- [x] Consulting tab
    - [x] Describe my skills and the contexts where I can be a useful consultant
    - [x] Include past consulting (iUNU, BrdgAI, Scope3) – separate by Entomology vs. Coding
    - [x] Include rates (plus discount for academics and the special offer for graduate students)

**Comment by njlyon0** [comment]
## Consulting Tab Done!

Finished the consulting tab, or at least a solid first draft of it.

## Portfolio Tab Needed?

I'm waffling on whether I need a portfolio tab. Isn't my portfolio this website and the stuff it contains? I want to think about it a bit more but I'm leaning towards forgoing one at this point and closing this issue

**Comment by njlyon0** [comment]
## Decision - No Portfolio Tab (For Now)

I've sort of threaded my portfolio throughout the existing pages (especially with the addition of the consulting tab) so I don't think a standalone portfolio is really needed at this point. I can always revisit later if my thoughts change
